define(function(){    
    var tableAndConfigOfBarAndLine = function(){
        var table = [
                        '<div class="tab-content">',
                            '<div role="tabpanel" class="tab-pane bhjj" id="param" style="display: block;">',
                                '<div class="col-xs-1">',
                                    '<ul class="nav nav-tabs tabs-left">',
                                        '<li class="active"><a href="#option01" data-toggle="tab">标题</a></li>',
                                        '<li><a href="#option02" data-toggle="tab">提示框</a></li>',
                                        '<li><a href="#option03" data-toggle="tab">图表背景</a></li>',
                                    '</ul>',
                                '</div>',
                                '<div class="col-xs-11" style="height:350px;overflow:auto;" id="chartConfig">',
                                    '<div class="tab-content">',
                                        '<div class="tab-pane active" id="option01" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">主标题</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >内容&nbsp;&nbsp;</label>',
                                                        '<input class="form-control" v-model="optionSetting.titleContent">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >上边距&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.titleTop">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >位置&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleX">',
                                                            '<option>left</option>',
                                                            '<option>center</option>',
                                                            '<option>right</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.titleFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >风格&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontStyle">',
                                                            '<option>normal</option>',
                                                            '<option>italic</option>',
                                                            '<option>oblique</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="titleFontColor" v-model="optionSetting.titleFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">副标题</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >内容&nbsp;&nbsp;</label>',
                                                        '<input class="form-control" v-model="optionSetting.subtitleContent">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.subtitleFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >风格&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontStyle">',
                                                            '<option>normal</option>',
                                                            '<option>italic</option>',
                                                            '<option>oblique</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="subtitleFontColor" v-model="optionSetting.subtitleFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                        '</div>',
                                        '<div class="tab-pane" id="option02" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">提示框</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >是否显示&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipShow">',
                                                            '<option>true</option>',
                                                            '<option>false</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >边框颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipBorderColor" v-model="optionSetting.tooltipBorderColor"/>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >边框宽度&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.tooltipBorderWidth">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >背景颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipBackgroundColor" v-model="optionSetting.tooltipBackgroundColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">提示框样式</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.tooltipFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipFontColor" v-model="optionSetting.tooltipFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                        '</div>',
                                        '<div class="tab-pane" id="option03" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">其他</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<table>',
                                                    '<tr>',
                                                        '<td class="col-md-3">透明</td><td><input type="range" id="backgroundOpacity" min="0" max="100" v-model="optionSetting.backgroundOpacity"/></td><td class="col-md-3">不透明</td>',
                                                    '</tr>',
                                                    '<tr></tr>',
                                                    '<tr>',
                                                        '<td class="col-md-3">轴标签旋转</td><td><input type="range" id="xRotate" min="-90" max="90" v-model="optionSetting.xRotate"/></td>',
                                                    '</tr>',
                                                    '<tr></tr>',
                                                    '<tr>',
                                                        '<div class="form-group form-group-sm">',
                                                            '<label >Y轴单位&nbsp;&nbsp;</label>',
                                                            '<input class="form-control" v-model="optionSetting.yAxisContent">',
                                                        '</div>',
                                                    '</tr>',
                                                '</table>',
                                            '</div>',
                                        '</div>',
                                    '</div>',
                                '</div>',
                            '</div>',
                        '</div>',
                        '</div>'].join("");
        return table;
    };

    var tableAndConfigOfPie = function(){
        var table = [
                    '<div class="tab-content">',
                        '<div role="tabpanel" class="tab-pane bhjj" id="param" style="display: block;">',
                            '<div class="col-xs-1">',
                                '<ul class="nav nav-tabs tabs-left">',
                                    '<li class="active"><a href="#option01" data-toggle="tab">标题</a></li>',
                                    '<li><a href="#option02" data-toggle="tab">提示框</a></li>',
                                    '<li><a href="#option03" data-toggle="tab">图例项</a></li>',
                                    '<li><a href="#option04" data-toggle="tab">图表背景</a></li>',
                                '</ul>',
                            '</div>',
                        '<div class="col-xs-11" style="height:350px;overflow:auto;" id="chartConfig">',
                            '<div class="tab-content">',
                                '<div class="tab-pane active" id="option01" style="padding-top: 0px">',
                                    '<div>',
                                        '<span style="color:#5D5BA8;margin-top:10px;">主标题</span>',
                                        '<hr style="margin-top:10px;">',
                                        '<form role="form">',
                                            '<div class="form-group form-group-sm">',
                                                '<label >内容&nbsp;&nbsp;</label>',
                                                '<input class="form-control" v-model="optionSetting.titleContent">',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >上边距&nbsp;&nbsp;</label>',
                                                '<input type="number" class="form-control" v-model="optionSetting.titleTop">',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >位置&nbsp;&nbsp;</label>',
                                                '<select class="form-control" v-model="optionSetting.titleX">',
                                                    '<option>left</option>',
                                                    '<option>center</option>',
                                                    '<option>right</option>',
                                                '</select>',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >字体&nbsp;&nbsp;</label>',
                                                '<select class="form-control" v-model="optionSetting.titleFontFamily">',
                                                    '<option>SimSun</option>',
                                                    '<option>Microsoft YaHei</option>',
                                                    '<option>sans-serif</option>',
                                                    '<option>SimHei</option>',
                                                    '<option>KaiTi</option>',
                                                '</select>',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >字号&nbsp;&nbsp;</label>',
                                                '<input type="number" class="form-control" v-model="optionSetting.titleFontSize">',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >粗细&nbsp;&nbsp;</label>',
                                                '<select class="form-control" v-model="optionSetting.titleFontWeight">',
                                                    '<option>normal</option>',
                                                    '<option>bold</option>',
                                                    '<option>bolder</option>',
                                                    '<option>lighter</option>',
                                                '</select>',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >风格&nbsp;&nbsp;</label>',
                                                '<select class="form-control" v-model="optionSetting.titleFontStyle">',
                                                    '<option>normal</option>',
                                                    '<option>italic</option>',
                                                    '<option>oblique</option>',
                                                '</select>',
                                            '</div>',
                                            '<div class="form-group form-group-sm">',
                                                '<label >文字颜色&nbsp;&nbsp;</label>',
                                                '<input type="text" id="titleFontColor" v-model="optionSetting.titleFontColor"/>',
                                            '</div>',
                                        '</form>',
                                    '</div>',
                                '<div>',
                                    '<span style="color:#5D5BA8;margin-top:10px;">副标题</span>',
                                    '<hr style="margin-top:10px;">',
                                    '<form role="form">',
                                        '<div class="form-group form-group-sm">',
                                            '<label >内容&nbsp;&nbsp;</label>',
                                            '<input class="form-control" v-model="optionSetting.subtitleContent">',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >字体&nbsp;&nbsp;</label>',
                                            '<select class="form-control" v-model="optionSetting.subtitleFontFamily">',
                                                '<option>SimSun</option>',
                                                '<option>Microsoft YaHei</option>',
                                                '<option>sans-serif</option>',
                                                '<option>SimHei</option>',
                                                '<option>KaiTi</option>',
                                            '</select>',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >字号&nbsp;&nbsp;</label>',
                                            '<input type="number" class="form-control" v-model="optionSetting.subtitleFontSize">',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >粗细&nbsp;&nbsp;</label>',
                                            '<select class="form-control" v-model="optionSetting.subtitleFontWeight">',
                                                '<option>normal</option>',
                                                '<option>bold</option>',
                                                '<option>bolder</option>',
                                                '<option>lighter</option>',
                                            '</select>',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >风格&nbsp;&nbsp;</label>',
                                            '<select class="form-control" v-model="optionSetting.subtitleFontStyle">',
                                                '<option>normal</option>',
                                                '<option>italic</option>',
                                                '<option>oblique</option>',
                                            '</select>',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >文字颜色&nbsp;&nbsp;</label>',
                                            '<input type="text" id="subtitleFontColor" v-model="optionSetting.subtitleFontColor"/>',
                                        '</div>',
                                    '</form>',
                                '</div>',
                            '</div>',
                            '<div class="tab-pane" id="option02" style="padding-top: 0px">',
                                '<div>',
                                    '<span style="color:#5D5BA8;margin-top:10px;">提示框</span>',
                                    '<hr style="margin-top:10px;">',
                                    '<form role="form">',
                                        '<div class="form-group form-group-sm">',
                                            '<label >是否显示&nbsp;&nbsp;</label>',
                                            '<select class="form-control" data-bind="options: tooltipShow, value: selectedToolTipShow, valueUpdate: \'keyup\'"></select>',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >边框颜色&nbsp;&nbsp;</label>',
                                            '<input type="text" id="tooltipBorderColor" data-bind="value: tooltipBorderColor, valueUpdate: \'input\'"/>',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >边框宽度&nbsp;&nbsp;</label>',
                                            '<input type="number" class="form-control" data-bind="value: tooltipBorderWidth, valueUpdate: \'input\'">',
                                        '</div>',
                                        '<div class="form-group form-group-sm">',
                                            '<label >背景颜色&nbsp;&nbsp;</label>',
                                            '<input type="text" id="tooltipBackgroundColor" data-bind="value: tooltipBackgroundColor, valueUpdate: \'input\'"/>',
                                        '</div>',
                                    '</form>',
                                '</div>',
                                '<div>',
                                    '<span style="color:#5D5BA8;margin-top;10px;">提示框样式</span>',
                                    '<hr style="margin-top:10px;">',
                                    '<form role="form">',
                                    '<div class="form-group form-group-sm">',
                                        '<label >字体&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: tooltipFontFamily, value: selectedToolTipFontFamily, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >字号&nbsp;&nbsp;</label>',
                                        '<input type="number" class="form-control" data-bind="value: tooltipFontSize, valueUpdate: \'input\'">',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >粗细&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: tooltipFontWeight, value: selectedToolTipFontWeight, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                        '<input type="text" id="tooltipFontColor" data-bind="value: tooltipFontColor, valueUpdate: \'input\'"/>',
                                    '</div>',
                                '</form>',
                            '</div>',
                        '</div>',
                        '<div class="tab-pane" id="option03" style="padding-top: 0px">',
                            '<div>',
                                '<span style="color:#5D5BA8;margin-top;10px;">图例项</span>',
                                '<hr style="margin-top:10px;">',
                                '<form role="form">',
                                    '<div class="form-group form-group-sm">',
                                        '<label >图标间距&nbsp;&nbsp;</label>',
                                        '<input type="number" min="1" class="form-control" data-bind="value: legendItemGap, valueUpdate: \'input\'">',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >图标样式&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: legendIcon, value: selectedLegendIcon, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >字体&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: legendFontFamily, value: selectedLegendFontFamily, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >字号&nbsp;&nbsp;</label>',
                                        '<input type="number" class="form-control" data-bind="value: legendFontSize, valueUpdate: \'input\'">',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >粗细&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: legendFontWeight, value: selectedLegendFontWeight, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                        '<input type="text" id="legendFontColor" data-bind="value: legendFontColor, valueUpdate: \'input\'"/>',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >上边距&nbsp;&nbsp;</label>',
                                        '<input type="number" class="form-control" data-bind="value: legendTop, valueUpdate: \'input\'">',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >左边距&nbsp;&nbsp;</label>',
                                        '<input type="number" class="form-control" data-bind="value: legendLeft, valueUpdate: \'input\'">',
                                    '</div>',
                                    '<div class="form-group form-group-sm">',
                                        '<label >布局方式&nbsp;&nbsp;</label>',
                                        '<select class="form-control" data-bind="options: legendOrient, value: selectedLegendOrient, valueUpdate: \'keyup\'"></select>',
                                    '</div>',
                                '</form>',
                            '</div>',
                        '</div>',
                        '<div class="tab-pane" id="option04" style="padding-top: 0px">',
                            '<div>',
                                '<span style="color:#5D5BA8;margin-top;10px;">其他</span>',
                                '<hr style="margin-top:10px;">',
                                '<table>',
                                    '<tr>',
                                        '<td class="col-md-3">透明</td><td><input type="range" id="backgroundOpacity" min="0" max="100" data-bind="value: backgroundOpacity, valueUpdate: \'input\'"/></td><td class="col-md-3">不透明</td>',
                                    '</tr>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>'].join("");

        return table;
    };

    var tableAndConfigOfText = function(){
        var table = [
            '<ul class="nav nav-tabs" role="tablist">',
                '<li role="presentation" class="active"><a href="#param" data-toggle="tab">配置项</a></li>',
            '</ul>',
            '<div class="col-xs-11" style="height:350px;overflow:auto;" id="chartConfig">',
                '<form role="form">',
                    '<div class="form-group form-group-sm">',
                        '<label >文字内容&nbsp;&nbsp;</label>',
                        '<input class="form-control" data-bind="value: text, valueUpdate: \'keyup\'">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >文字颜色&nbsp;&nbsp;</label>',
                        '<input id="textColor" class="form-control" data-bind="value: textColor, valueUpdate: \'input\'">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >文字大小&nbsp;&nbsp;<span id="textFontSize"></span></label>',
                        '<input type="range" class="form-control" data-bind="value: fontSize, valueUpdate: \'keyup\'">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >背景颜色&nbsp;&nbsp;</label>',
                        '<input id="tagColor" class="form-control"  data-bind="value: color, valueUpdate: \'keyup\'">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >边框颜色&nbsp;&nbsp;</label>',
                        '<input id="tagStrokeColor" class="form-control"  data-bind="value: strokeColor, valueUpdate: \'keyup\'">',
                    '</div>',
                '</form>',
            '</div>'
            ].join("");

        return table;
    };

    var tableAndConfigOfSubGroup = function(){
        var table = [
            '<form role="form">',
            '<div class="form-group form-group-sm">',
            '<label >文字内容&nbsp;&nbsp;</label>',
            '<input class="form-control" data-bind="value: subGroupText, valueUpdate: \'keyup\'">',
            '</div>',
            '<div class="form-group form-group-sm">',
            '<label >文字颜色&nbsp;&nbsp;</label>',
            '<input id="subGroupTextColor" class="form-control" data-bind="value: subGroupTextColor, valueUpdate: \'input\'">',
            '</div>',
            '<div class="form-group form-group-sm">',
            '<label >文字大小&nbsp;&nbsp;<span id="subGroupFontSize"></span></label>',
            '<input type="range" class="form-control" data-bind="value: subGroupFontSize, valueUpdate: \'keyup\'">',
            '</div>',
            '<div class="form-group form-group-sm">',
            '<label >图片宽度&nbsp;&nbsp;</label>',
            '<input type="range" min="0" max="448" class="form-control" data-bind="value: subGroupImageWidth, valueUpdate: \'keyup\'">',
            '</div>',
            '<div class="form-group form-group-sm">',
            '<label >图片高度&nbsp;&nbsp;</label>',
            '<input type="range" min="0" max="410" class="form-control" data-bind="value: subGroupImageHeight, valueUpdate: \'keyup\'">',
            '</div>',
            '</form>'
        ].join("");

        return table;
    };

    var resetCanvasTagOfImage = function(){
        var table = [
            '<div id="subGroupContainer" style="width:40%;height:410px;float:left;background-color: rgb(238,238,238);overflow: auto">',
            '<div id="subGroupLoading" class="loader-container text-center color-black" style="display: none;">',
            '<div><i class="fa fa-spinner fa-pulse fa-3x"></i></div>',
            '<div>正在加载图片...</div>',
            '</div>',
            '</div>',
            '<div id="subGroupOptionPanel" style="width:50%;height:410px;float:left;margin-left:50px;">',
            '<ul class="nav nav-tabs" role="tablist">',
            '<li role="presentation" class="active"><a href="#param" data-toggle="tab">配置项</a></li>',
            '</ul>',
            '<div class="col-xs-11" style="height:350px;overflow:auto;margin-top: 10px;" id="subGroupConfig">',
            '<div>',
            '<form enctype="multipart/form-data" id="imgFile">',
            '<input name="imgFile" type="file" />',
            '<button type="reset" class="btn btn-sm btn-warning" style="margin-left: 10px;float: right">重置</button>',
            '<button type="button" class="btn btn-sm btn-success" style="float: right">上传</button>',
            '<p class="help-block">请上传组件图片.</p>',
            '</form>',
            '</div>',
            '<div></div>',
            '</div>',
            '</div>'
        ].join("");
        
      return table;  
    };
                    
	return {
        tableAndConfigOfBarAndLine : tableAndConfigOfBarAndLine,
        tableAndConfigOfPie : tableAndConfigOfPie,
        tableAndConfigOfText : tableAndConfigOfText,
        tableAndConfigOfSubGroup : tableAndConfigOfSubGroup,
        resetCanvasTagOfImage : resetCanvasTagOfImage
	};
});