define(function(){    
    var tableAndConfigOfBarAndLine = function(){
        var table = [
                        '<div class="tab-content">',
                            '<div role="tabpanel" class="tab-pane bhjj" id="param" style="display: block;">',
                                '<div class="col-xs-1">',
                                    '<ul class="nav nav-tabs tabs-left">',
                                        '<li class="active"><a href="#option01" data-toggle="tab">标题</a></li>',
                                        '<li><a href="#option02" data-toggle="tab">提示框</a></li>',
                                        '<li><a href="#option03" data-toggle="tab">图表背景</a></li>',
                                    '</ul>',
                                '</div>',
                                '<div class="col-xs-11" style="height:350px;overflow:auto;" id="chartConfig">',
                                    '<div class="tab-content">',
                                        '<div class="tab-pane active" id="option01" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">主标题</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >内容&nbsp;&nbsp;</label>',
                                                        '<input class="form-control" v-model="optionSetting.titleContent">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >上边距&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.titleTop">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >位置&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleX">',
                                                            '<option>left</option>',
                                                            '<option>center</option>',
                                                            '<option>right</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.titleFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >风格&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.titleFontStyle">',
                                                            '<option>normal</option>',
                                                            '<option>italic</option>',
                                                            '<option>oblique</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="titleFontColor" v-model="optionSetting.titleFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">副标题</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >内容&nbsp;&nbsp;</label>',
                                                        '<input class="form-control" v-model="optionSetting.subtitleContent">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.subtitleFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >风格&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.subtitleFontStyle">',
                                                            '<option>normal</option>',
                                                            '<option>italic</option>',
                                                            '<option>oblique</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="subtitleFontColor" v-model="optionSetting.subtitleFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                        '</div>',
                                        '<div class="tab-pane" id="option02" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">提示框</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >是否显示&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipShow">',
                                                            '<option>true</option>',
                                                            '<option>false</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >边框颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipBorderColor" v-model="optionSetting.tooltipBorderColor"/>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >边框宽度&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.tooltipBorderWidth">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >背景颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipBackgroundColor" v-model="optionSetting.tooltipBackgroundColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">提示框样式</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<form role="form">',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字体&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipFontFamily">',
                                                            '<option>SimSun</option>',
                                                            '<option>Microsoft YaHei</option>',
                                                            '<option>sans-serif</option>',
                                                            '<option>SimHei</option>',
                                                            '<option>KaiTi</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >字号&nbsp;&nbsp;</label>',
                                                        '<input type="number" class="form-control" v-model="optionSetting.tooltipFontSize">',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >粗细&nbsp;&nbsp;</label>',
                                                        '<select class="form-control" v-model="optionSetting.tooltipFontWeight">',
                                                            '<option>normal</option>',
                                                            '<option>bold</option>',
                                                            '<option>bolder</option>',
                                                            '<option>lighter</option>',
                                                        '</select>',
                                                    '</div>',
                                                    '<div class="form-group form-group-sm">',
                                                        '<label >文字颜色&nbsp;&nbsp;</label>',
                                                        '<input type="text" id="tooltipFontColor" v-model="optionSetting.tooltipFontColor"/>',
                                                    '</div>',
                                                '</form>',
                                            '</div>',
                                        '</div>',
                                        '<div class="tab-pane" id="option03" style="padding-top: 0px">',
                                            '<div>',
                                                '<span style="color:#5D5BA8;margin-top:10px;">其他</span>',
                                                '<hr style="margin-top:10px;">',
                                                '<table>',
                                                    '<tr>',
                                                        '<td class="col-md-3">透明</td><td><input type="range" id="backgroundOpacity" min="0" max="100" v-model="optionSetting.backgroundOpacity"/></td><td class="col-md-3">不透明</td>',
                                                    '</tr>',
                                                    // '<tr></tr>',
                                                    // '<tr>',
                                                    //     '<td class="col-md-3">轴标签旋转</td><td><input type="range" id="xRotate" min="-90" max="90" v-model="optionSetting.xRotate"/></td>',
                                                    // '</tr>',
                                                    // '<tr></tr>',
                                                    // '<tr>',
                                                    //     '<div class="form-group form-group-sm">',
                                                    //         '<label >Y轴单位&nbsp;&nbsp;</label>',
                                                    //         '<input class="form-control" v-model="optionSetting.yAxisContent">',
                                                    //     '</div>',
                                                    // '</tr>',
                                                '</table>',
                                            '</div>',
                                        '</div>',
                                    '</div>',
                                '</div>',
                            '</div>',
                        '</div>',
                        '</div>'].join("");
        return table;
    };

    var tableAndConfigOfText = function(){
        var table = [
            '<div class="col-xs-11" style="height:350px;overflow:auto;" id="chartConfig">',
                '<form role="form">',
                    '<div class="form-group form-group-sm">',
                        '<label >文字内容&nbsp;&nbsp;</label>',
                        '<input class="form-control" v-model="optionSetting.text">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >文字颜色&nbsp;&nbsp;</label>',
                        '<input id="textColor" class="form-control" v-model="optionSetting.textColor">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >文字大小&nbsp;&nbsp;<span id="textFontSize"></span></label>',
                        '<input type="range" class="form-control" v-model="optionSetting.fontSize">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >背景颜色&nbsp;&nbsp;</label>',
                        '<input id="tagColor" class="form-control"  v-model="optionSetting.color">',
                    '</div>',
                    '<div class="form-group form-group-sm">',
                        '<label >边框颜色&nbsp;&nbsp;</label>',
                        '<input id="tagStrokeColor" class="form-control"  v-model="optionSetting.strokeColor">',
                    '</div>',
                '</form>',
            '</div>'
            ].join("");

        return table;
    };

    var tableAndConfigOfSubGroup = function(){
        var table = [
            '<form role="form">',
                '<div class="form-group form-group-sm">',
                    '<label >文字内容&nbsp;&nbsp;</label>',
                    '<input class="form-control" v-model="optionSetting.subGroupText">',
                '</div>',
                '<div class="form-group form-group-sm">',
                    '<label >文字颜色&nbsp;&nbsp;</label>',
                    '<input id="subGroupTextColor" class="form-control" v-model="optionSetting.subGroupTextColor">',
                '</div>',
                '<div class="form-group form-group-sm">',
                    '<label >文字大小&nbsp;&nbsp;<span id="subGroupFontSize"></span></label>',
                    '<input type="range" class="form-control" v-model="optionSetting.subGroupFontSize">',
                '</div>',
            '</form>'
        ].join("");

        return table;
    };
                    
	return {
        tableAndConfigOfBarAndLine : tableAndConfigOfBarAndLine,
        tableAndConfigOfText : tableAndConfigOfText,
        tableAndConfigOfSubGroup : tableAndConfigOfSubGroup
	};
});